name: untitled1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
#haifan ganteng
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2 
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # UI & logic
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  image_picker: ^1.1.2
  get: ^4.7.2
  path_provider: ^2.1.5
  image: ^4.5.4
  animations: ^2.0.11
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/menu/nav-camera.svg
    - assets/menu/styling.svg
    - assets/menu/wardrobe.svg
    - assets/menu/icon-color-styling.svg
    - assets/menu/icon-color-wardrobe.svg
    - assets/iconfitur/buttonsaveoutfits.svg
    - assets/iconfitur/redo.svg
    - assets/iconfitur/reload.svg
    - assets/iconfitur/undo.svg
    - assets/iconfitur/takephoto.svg
    - assets/iconfitur/photolibrary.svg
    - assets/iconfitur/arrowleft.svg
    - assets/iconfitur/bann.png
    - assets/iconfitur/google-button.svg
    - assets/iconfitur/user-profile.svg
    - assets/category/all.svg
    - assets/category/tops.svg
    - assets/category/bottoms.svg
    - assets/category/outwear.svg
    - assets/category/footwear.svg
